version: 0.1.1-{build}

branches:
  except:
    - doc

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\dishub

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release
  - cp target\release\dishub.exe dishub-v0.1.1.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note dishub-v0.1.1.exe

test: off
test_script:
  - cargo test --verbose --release

artifacts:
  - path: dishub-v0.1.1.exe

deploy:
  provider: GitHub
  artifact: dishub-v0.1.1.exe
  auth_token:
    secure: CrgimtpWQY7eIfVAMBBjQKfeKLBswUwT7cDlXKMszMj6DsuJvIeFou6gyoft5s7/
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
