.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DISHUB\-UNFOLLOW\-FEEDS" "1" "November 2016" "dishub developers" ""
.
.SH "NAME"
\fBdishub\-unfollow\-feeds\fR \- Posting GitHub activity on Discord \- unfollowing
.
.SH "SYNOPSIS"
\fBdishub\fR \fIOPTIONS\fR \fBunfollow\-feeds\fR
.
.SH "DESCRIPTION"
Unfollow a user or a repository and stop posting them to Discord\.
.
.P
For description of \fBdishub\fR itself see dishub(1)\.
.
.SH "OPTIONS"
See dishub(1)\.
.
.SH "EXAMPLES"
\fBdishub unfollow\-feeds\fR
.
.IP "" 4
.
.nf

Stop following nabijaczleweli and nabijaczleweli/dishub:

  The feeds currently subscribed to:
    nabijaczleweli
    nabijaczleweli/dishub
    nabijaczleweli/cargo\-update
    nabijaczleweli/safe\-transmute\-rs

  The feed to unsubscribe from (or empty to end): nabijaczleweli/dishub
  The feed to unsubscribe from (or empty to end): nabijaczleweli
  The feed to unsubscribe from (or empty to end):
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/dishub/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/dishub\fR>
