.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DISHUB" "1" "April 2018" "dishub developers" ""
.
.SH "NAME"
\fBdishub\fR \- Posting GitHub activity on Discord
.
.SH "SYNOPSIS"
\fBdishub\fR \fIOPTIONS\fR <SUBSYSTEM> [SUBSYSTEM_OPTIONS]
.
.SH "DESCRIPTION"
Dishub is an app for posting GitHub activity on Discord\.
.
.P
See the subcommands for more information:
.
.IP "\(bu" 4
dishub\-init(1) \- authorising the application
.
.IP "\(bu" 4
dishub\-add\-feeds(1) \- following people and repositories
.
.IP "\(bu" 4
dishub\-unfollow\-feeds(1) \- following people and repositories
.
.IP "\(bu" 4
dishub\-start\-daemon(1) \- start the tweet\-posting daemon
.
.IP "" 0
.
.SH "OPTIONS"
\-c \-\-config\-dir <\fIconfig_dir\fR>
.
.IP "" 4
.
.nf

Directory with the configuration\.

The configuration directory contains all of dishub\'s data\.

Default: $HOME/\.dishub
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
See the per\-subcommand examples page
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/dishub/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/dishub\fR>
