.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DISHUB\-START\-DAEMON" "1" "April 2018" "dishub developers" ""
.
.SH "NAME"
\fBdishub\-start\-daemon\fR \- Posting GitHub activity on Discord \- posting
.
.SH "SYNOPSIS"
\fBdishub\fR \fIOPTIONS\fR \fBstart\-daemon\fR \fISTART_DAEMON_OPTIONS\fR
.
.SH "DESCRIPTION"
Start the daemon that will queue and post events to Discord,
.
.P
Requires tokens to be set, so be sure to run dishub\-init(1) beforehand\.
.
.P
Will, of course, not post anything until you run dishub\-add\-feeds(1)\.
.
.P
Loops forever and doesn\'t terminate but with a Ctrl\-C equivalent\.
.
.P
For description of \fBdishub\fR itself see `dishub(1)\.
.
.SH "OPTIONS"
See dishub(1)\.
.
.SH "START_DAEMON_OPTIONS"
\-s \-\-sleep <\fIsleep_time\fR>
.
.IP "" 4
.
.nf

Time to wait between checking for and posting events\.

Default: 60s\. Format: NNs\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
\fBdishub start\-daemon\fR
.
.IP "" 4
.
.nf

Successfully sent 14 events from nabijaczleweli
Successfully sent 7 events from nabijaczleweli/dishub
No new events in nabijaczleweli/cargo\-update
Too early to re\-poll nabijaczleweli/safe\-transmute\-rs
\.\.\.
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/dishub/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/dishub\fR>
